In [1]:
import numpy as np

#1
adj_matrix = np.array([
    [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0, 0, 1, 1, 0]
])
print("Ma trận kề:")
print(adj_matrix)

#2
graph = {
    '1':['3','4','5','6'],
    '2':['9','10'],
    '3':['1','8'],
    '4':['1','5','8'],
    '5':['1','4','9','10'],
    '6':['1','7','9'],
    '7':['6'],
    '8':['3','4','10'],
    '9':['2','5','6','10'],
    '10':['2','5','8','9']
}
print("Danh sách cạnh:")
print(graph)

#3
def bfs(adj_matrix, node):
    visited = []
    bfs = []
    bfs.append(node)
    visited.append(node)
    row, col = adj_matrix.shape
    for x in bfs:
        for i in range(col):
            if adj_matrix[x-1, i] == 1 and (i + 1 ) not in visited:
                bfs.append(i + 1)
                visited.append(i + 1)
            if len(bfs) == col:
                break
    return bfs

bfs_kq = bfs(adj_matrix, 5)
print("BFS bắt đầu từ đỉnh 5:", bfs_kq)

#4
vst = set()
def dfs(graph, vst, node):
    if node not in vst:
        print(node)
        vst.add(node)
        for k in graph[node]:
            dfs(graph, vst, k)

print("DFS bắt đầu từ đỉnh 7:")
dfs(graph, vst, '7')

Ma trận kề:
[[0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 1 0 0 1 0 0]
 [1 0 0 1 0 0 0 0 1 1]
 [1 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 1]
 [0 1 0 0 1 1 0 0 0 1]
 [0 1 0 0 1 0 0 1 1 0]]
Danh sách cạnh:
{'1': ['3', '4', '5', '6'], '2': ['9', '10'], '3': ['1', '8'], '4': ['1', '5', '8'], '5': ['1', '4', '9', '10'], '6': ['1', '7', '9'], '7': ['6'], '8': ['3', '4', '10'], '9': ['2', '5', '6', '10'], '10': ['2', '5', '8', '9']}
BFS bắt đầu từ đỉnh 5: [5, 1, 4, 9, 10, 3, 6, 8, 2, 7]
DFS bắt đầu từ đỉnh 7:
7
6
1
3
8
4
5
9
2
10


In [1]:
import numpy as np

#5
adj_matrix = np.array([
    [0, 1, 1, 1, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0]
])

print("Ma trận kề:")
print(adj_matrix)

#6
graph = {
    '1':['2','3','4'],
    '2':['5'],
    '3':['6'],
    '4':['3','5','7'],
    '5':['7'],
    '6':['7'],
    '7':[]
}
print("Danh sách cạnh:")
print(graph)

#7
def bfs(adj_matrix, node):
    visited = []
    bfs = []
    bfs.append(node)
    visited.append(node)
    row, col = adj_matrix.shape
    for x in bfs:
        for i in range(col):
            if adj_matrix[x-1, i] == 1 and (i + 1 ) not in visited:
                bfs.append(i + 1)
                visited.append(i + 1)
            if len(bfs) == col:
                break
    return bfs

bfs_kq = bfs(adj_matrix, 1)
print("BFS bắt đầu từ đỉnh 1:", bfs_kq)

#8
vst = set()
def dfs(graph, vst, node):
    if node not in vst:
        print(node)
        vst.add(node)
        for k in graph[node]:
            dfs(graph, vst, k)

print("DFS bắt đầu từ đỉnh 4:")
dfs(graph, vst, '4')

Ma trận kề:
[[0 1 1 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
Danh sách cạnh:
{'1': ['2', '3', '4'], '2': ['5'], '3': ['6'], '4': ['3', '5', '7'], '5': ['7'], '6': ['7'], '7': []}
BFS bắt đầu từ đỉnh 1: [1, 2, 3, 4, 5, 6, 7]
DFS bắt đầu từ đỉnh 4:
4
3
6
7
5


In [ ]:
def best_first_search(start, goal):
    # Hàm ước lượng h (số ô sai biệt)
    def heuristic(state, goal):
        return sum(1 for i in range(3) for j in range(3) if state[i][j] != goal[i][j] and state[i][j] != 0)
    
    # Các phép di chuyển có thể (lên, xuống, trái, phải)
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    
    # Danh sách ưu tiên
    priority_list = []
    priority_list.append((heuristic(start, goal), start))
    
    # Tập các trạng thái đã duyệt
    visited = set()
    visited.add(tuple(map(tuple, start)))
    
    # Lịch sử các trạng thái
    history = []
    
    while priority_list:
        # Lấy trạng thái có giá trị h thấp nhất
        priority_list.sort(key=lambda x: x[0])  # Sắp xếp danh sách theo giá trị h
        _, current = priority_list.pop(0)
        
        # Lưu trạng thái vào lịch sử
        history.append(current)
        
        if current == goal:
            return history
        
        # Tìm vị trí ô trống (0)
        empty_pos = next((i, j) for i in range(3) for j in range(3) if current[i][j] == 0)
        
        for move in moves:
            new_pos = (empty_pos[0] + move[0], empty_pos[1] + move[1])
            if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
                new_state = [list(row) for row in current]
                new_state[empty_pos[0]][empty_pos[1]], new_state[new_pos[0]][new_pos[1]] = new_state[new_pos[0]][new_pos[1]], new_state[empty_pos[0]][empty_pos[1]]
                
                new_tuple_state = tuple(map(tuple, new_state))
                if new_tuple_state not in visited:
                    priority_list.append((heuristic(new_state, goal), new_state))
                    visited.add(new_tuple_state)
    
    return None

def print_state(state):
    for row in state:
        print(' '.join(str(x) for x in row))
    print()

# Ví dụ sử dụng
start = [
    [0, 2, 3],
    [4, 1, 5],
    [7, 8, 6]
]

goal = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]

history = best_first_search(start, goal)
if history:
    print("Đã tìm thấy giải pháp! Các trạng thái đã duyệt:")
else:
    print("Không tìm thấy giải pháp.")