In [8]:
#1)
n=int(input("Nhập n:"))
tong=0
for i in range(1,n+1):
    tong+=i
print(tong)
tich=1
for i in range(1,n+1):
    tich*=i
print(tich)

Nhập n:  5


15
120


In [12]:
#2)
c = 0
d = 0
for i in range(1,1001):
    if i % 2 == 0:
        c-=i
    else:
        d+=i
print(c+d)

-500


In [1]:
#3)
nam=int(input("Nhập năm:"))
if nam>=1900 and nam<=3000:
    if nam % 4 == 0 and nam % 100 != 0 or nam % 400 == 0:
        print("Đây là năm nhuận")
    else:
        print("Đây không phải năm nhuận")
else:
     print("Mời nhập lại năm trong khoảng 1900-3000")

Nhập năm: 2016


Đây là năm nhuận


In [13]:
#4)
print("1. Chuyển đổi từ độ C sang độ F")
print("2. Chuyển đổi từ độ F sang độ C")
lua_chon = input("Nhập lựa chọn của bạn [1 hoặc 2]:")
if lua_chon=='1':
    do_c = float(input("Nhập độ C: "))
    do_f = (do_c * 9/5) + 32
    print(f"{do_c} độ C = {do_f} độ F")
elif lua_chon=='2':
    do_f = float(input("Nhập độ F: "))
    do_c = (do_f - 32) * 5/9
    print(f"{do_f} độ F = {do_c} độ C")
else:
    print("Lựa chọn không hợp lệ. Vui lòng chọn 1 hoặc 2.")

1. Chuyển đổi từ độ C sang độ F
2. Chuyển đổi từ độ F sang độ C


Nhập lựa chọn của bạn [1 hoặc 2]: 2
Nhập độ F:  78


78.0 độ F = 25.555555555555557 độ C


In [10]:
#5)
def count_digits(n):
    num_str = str(n)
    return len(num_str)
while True:
    try:
        num = int(input("Nhập một số nguyên dương:"))
        if num <= 0:
            print("Vui lòng nhập số nguyên dương.")
        else:
            break
    except ValueError:
        print("Vui lòng nhập một số nguyên dương.")
num_digits = count_digits(num)
print(f"Số chữ số của {num} là: {num_digits}")

Nhập một số nguyên dương:  2332323232


Số chữ số của 2332323232 là: 10


In [15]:
#6)
def reverse_number(n):
    reversed_num = 0
    while n > 0:
        # Lấy chữ số cuối cùng của n và thêm vào reversed_num
        last_digit = n % 10
        reversed_num = reversed_num * 10 + last_digit
        # Loại bỏ chữ số cuối cùng của n
        n //= 10
    return reversed_num
    
while True:
    try:
        num = int(input("Nhập một số nguyên dương:"))
        if num <= 0:
            print("Vui lòng nhập số nguyên dương.")
        else:
            break
    except ValueError:
        print("Vui lòng nhập một số nguyên dương.")
reversed_num = reverse_number(num)
print(f"Số đảo ngược của {num} là: {reversed_num}")

Nhập một số nguyên dương: 987654


Số đảo ngược của 987654 là: 456789


In [20]:
#7)
def decimal_to_binary(n):
    return bin(n)[2:]
def binary_to_decimal(binary):
    return int(binary, 2)
print("1. Chuyển đổi từ hệ 10 sang hệ 2")
print("2. Chuyển đổi từ hệ 2 sang hệ 10")
lua_chon = input("Nhập lựa chọn của bạn [1 hoặc 2]:")
if lua_chon=='1':
    d_number = int(input("Nhập số thập phân:"))
    b_number = decimal_to_binary(d_number)
    print(f"Số nhị phân của {d_number} là: {b_number}")
elif lua_chon=='2':
    b_number = input("Nhập số nhị phân:")
    d_number = binary_to_decimal(b_number)
    print(f"Số thập phân của {b_number} là: {d_number}")
else:
    print("Lựa chọn không hợp lệ. Vui lòng chọn 1 hoặc 2.")

1. Chuyển đổi từ hệ 10 sang hệ 2
2. Chuyển đổi từ hệ 2 sang hệ 10


Nhập lựa chọn của bạn [1 hoặc 2]: 4


Lựa chọn không hợp lệ. Vui lòng chọn 1 hoặc 2.


In [23]:
#8)
import math
def tinhNghiemPTBacHai(a, b, c):
    delta = float(b*b-4*a*c)
    if delta < 0:
        return "Phương trình vô nghiệm."
    elif delta == 0:
        # Nếu delta = 0, phương trình có nghiệm kép
        x = -b / (2*a)
        return f"Phương trình có nghiệm kép x = {x}"
    else:
        # Nếu delta > 0, phương trình có hai nghiệm phân biệt
        x1 = (-b + math.sqrt(delta)) / (2*a)
        x2 = (-b - math.sqrt(delta)) / (2*a)
        return f"Phương trình có 2 nghiệm phân biệt: x1 = {x1}, x2 = {x2}"
print("Mời nhập")
a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
c = float(input("Nhập c: "))
print(tinhNghiemPTBacHai(a, b, c))

Mời nhập


Nhập a:  1
Nhập b:  0
Nhập c:  -4


Phương trình có 2 nghiệm phân biệt: x1 = 2.0, x2 = -2.0


In [11]:
#9)
def ThuaSoNguyenTo(n):
    thuaSo = []
    while n % 2 == 0:
        thuaSo.append(2)
        n //= 2
    for i in range(3, int(n**0.5) + 1, 2):
        while n % i == 0:
            thuaSo.append(i)
            n //= i
    if n > 2:
       thuaSo.append(n)
    return thuaSo
    
while True:
    try:
        s = int(input("Nhập một số nguyên dương:"))
        if s <= 0:
            print("Vui lòng nhập số nguyên dương.")
        else:
            break
    except ValueError:
        print("Vui lòng nhập một số nguyên dương.")
thuaSo = ThuaSoNguyenTo(s)
if len(thuaSo) == 1:
    print(f"{s} là số nguyên tố.")
else:
    print(f"Các thừa số nguyên tố của {s} là:", end=" ")
    print(*thuaSo, sep=", ")

Nhập một số nguyên dương:  65


Các thừa số nguyên tố của 65 là: 5, 13


In [14]:
#10)
from datetime import datetime, timedelta
def previous_and_next_date(date_str):
    date_obj = datetime.strptime(date_str, "%d/%m/%Y")
    previous_date = date_obj - timedelta(days=1)
    next_date = date_obj + timedelta(days=1)
    return previous_date.strftime("%d/%m/%Y"), next_date.strftime("%d/%m/%Y")

date_input = input("Nhập ngày tháng năm (dd/mm/yyyy):")
try:
    previous, next = previous_and_next_date(date_input)
    print(f"Ngày liền trước: {previous}")
    print(f"Ngày liền sau: {next}")
except ValueError:
    print("Định dạng ngày không đúng. Vui lòng nhập lại theo định dạng dd/mm/yyyy.")

Nhập ngày tháng năm (dd/mm/yyyy): 7/8/2004


Ngày liền trước: 06/08/2004
Ngày liền sau: 08/08/2004


In [20]:
#11)
def main():
    # Nhập danh sách các số nguyên từ người dùng
    numbers = input("Nhập danh sách các số nguyên, cách nhau bằng dấu phẩy: ").split(',')
    numbers = [int(num.strip()) for num in numbers]  # Chuyển đổi các chuỗi thành số nguyên
    # Tính tổng các số
    total = sum(numbers)
    # Đếm số lượng số chẵn và số có 2 chữ số
    even_count = 0
    two_digit_count = 0
    for num in numbers:
        if num % 2 == 0:
            even_count += 1
        if 10 <= abs(num) <= 99:
            two_digit_count += 1
    print("Tổng các số:", total)
    print("Số lượng số chẵn:", even_count)
    print("Số lượng số có 2 chữ số:", two_digit_count)
    
if __name__ == "__main__":
    main()

Nhập danh sách các số nguyên, cách nhau bằng dấu phẩy:  111,323,22,110


Tổng các số: 566
Số lượng số chẵn: 2
Số lượng số có 2 chữ số: 1


In [11]:
#12)
def interchangeSort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(i + 1, n):
            if arr[i] > arr[j]:
                arr[i], arr[j] = arr[j], arr[i]
                
def bubbleSort(arr):
    n = len(arr)
    for i in range(n - 1):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]

def binarySort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        left, right = 0, i - 1
        while left <= right:
            mid = (left + right) // 2
            if arr[mid] < key:
                left = mid + 1
            else:
                right = mid - 1
        arr[left + 1:i + 1] = arr[left:i]
        arr[left] = key

list = [22,1,9,444,56]
interchangeSort(list)
print("Danh sách sau khi sắp xếp bằng Interchange sort:", list)
bubbleSort(list)
print("Danh sách sau khi sắp xếp bằng Bubble sort:", list)
binarySort(list)
print("Danh sách sau khi sắp xếp bằng Binary sort:", list)

Danh sách sau khi sắp xếp bằng Interchange sort: [1, 9, 22, 56, 444]
Danh sách sau khi sắp xếp bằng Bubble sort: [1, 9, 22, 56, 444]
Danh sách sau khi sắp xếp bằng Binary sort: [1, 9, 22, 56, 444]


In [12]:
#13
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

# Sử dụng
arr = [2, 3, 4, 10, 40]
target = 10
result = linear_search(arr, target)
if result != -1:
    print(f"Số {target} được tìm thấy tại vị trí {result}")
else:
    print(f"Số {target} không có trong danh sách")

def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

# Sử dụng
arr = [2, 3, 4, 10, 40]
target = 10
result = binary_search(arr, target)
if result != -1:
    print(f"Số {target} được tìm thấy tại vị trí {result}")
else:
    print(f"Số {target} không có trong danh sách")

Số 10 được tìm thấy tại vị trí 3
Số 10 được tìm thấy tại vị trí 3


In [13]:
#14)
def int_to_excel_column(n):
    result = ""
    while n > 0:
        remainder = (n - 1) % 26  # Chuyển từ 1-indexing sang 0-indexing và tính phần dư
        result = chr(65 + remainder) + result  # 65 là mã ASCII của ký tự 'A'
        n = (n - 1) // 26
    return result

# Nhập số nguyên từ người dùng
try:
    num = int(input("Nhập một số nguyên: "))
    if num <= 0:
        print("Vui lòng nhập một số nguyên dương.")
    else:
        excel_column = int_to_excel_column(num)
        print(f"Tên của cột trong Excel: {excel_column}")
except ValueError:
    print("Vui lòng nhập một số nguyên.")

Nhập một số nguyên:  77


Tên của cột trong Excel: BY


In [4]:
#15
import numpy as np
s = int(input("Nhập cấp của MT:"))
a = np.eye(s)
print(a)

Nhập cấp của MT: 5


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
